name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo ${GITHUB_WORKSPACE}
          echo "List files in GITHUB_WORKSPACE"
          ls ${GITHUB_WORKSPACE}
          echo "Pwd"
          pwd

  build:
    needs: [pre]
    runs-on: ubuntu-latest

    # Run a local ceramic nod to test against
    services:
      ceramic:
        image: ceramicnetwork/js-ceramic:3.2.0
        ports:
          - 7007:7007

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1
          cache: "yarn"
      - name: Install Packages
        run: yarn install
      - name: Run Tests
        run: yarn test
      - name: Run Linter
        run: yarn lint
      - name: Workarround for build error
        run: rm -rf node_modules/@tendermint
      - name: Run Build (ensure that build succeeds)
        run: yarn build
      - name: Run Ceramic Integration Tests
        run: yarn test:ceramic-integration
        env:
          CERAMIC_CLIENT_URL: ${{secrets.CERAMIC_CLIENT_URL}}

  check-provider-bitmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.8
          cache: "yarn"
      - name: Install Packages
        run: yarn install
      - name: Check provider bitmaps
        uses: ./.github/actions/check-provider-bitmaps
        with:
          ALCHEMY_API_KEY_OP: ${{ secrets.ALCHEMY_API_KEY_OP }}
          ALCHEMY_API_KEY_OP_SEPOLIA: ${{ secrets.ALCHEMY_API_KEY_OP_SEPOLIA }}
